name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Pull latest changes from remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config pull.rebase false
          git pull --allow-unrelated-histories https://Aniket2692:$HF_TOKEN@huggingface.co/spaces/Aniket2692/QA_RAG_BUDGET_PDF main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://Aniket2692:$HF_TOKEN@huggingface.co/spaces/Aniket2692/QA_RAG_BUDGET_PDF main
